apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false # if true image will push docker hub every new build
  insecureRegistries:
    - ticketing.hazi
  artifacts:
    - image: hazitgi/auth-ticketing
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .