apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: hazitgi/tickets
          imagePullPolicy: Never
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-values
                  key: jwt_key
            - name: DBHost
              valueFrom:
                secretKeyRef:
                  name: secret-values
                  key: dbhost
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-db-srv:27017/tickets'

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
